# Generated by Django 4.0.3 on 2023-12-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_admin_staff_role_student_mat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='student_id',
            new_name='mat_number',
        ),
        migrations.AlterUniqueTogether(
            name='bookreturn',
            unique_together={('student', 'book')},
        ),
    ]
