# Generated by Django 4.0.3 on 2023-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_student_id_userprofile_mat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mat_number',
            field=models.CharField(default='00000000', max_length=13),
        ),
    ]
