# Generated by Django 4.0.3 on 2023-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_userprofile_mat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
